
export const SET_LOADING = "SET_LOADING";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_TOAST = "SET_TOAST";
export const SET_CURRENT_ACTION = "SET_CURRENT_ACTION";
export const SET_CATEGORY_INPUT = "SET_CATEGORY_INPUT";



